### ISSUE TITLE
Registrar venda

### ISSUE THREAD

**Issue by amintasvrp** [JuanBarros2/estoque-facil-si1#7]
## Descrição
*Eu, como administrador, gostaria de registrar uma venda, informando os produtos, a quantidade de itens e registrando o valor total da venda (descontos devem ser considerados). O número de itens do produto deve ser decrementado.*

## Funcionalidade
O sistema deve permitir que o administrador registre uma venda. A quantidade de cada produto deve ser validada em relação a quantidade de produtos de estoque.

[ideia do componente](https://docs.google.com/drawings/d/1Nq_EDpJOb5XzH76U_xnksgeVsWpGj_tZ2d9Qy510m0A/edit?usp=sharing)

## Front
- [x] Carregar produtos do serviço GET _"/product"_;
- [x] Salvar venda POST _"/sale"_;
- [x] Implementar tela;

[ideia do componente]

## Back
- [x] Implementar serviço de registro da venda.

## Formato do JSON
Request POST: `{
	"items":[ {
                          "product": {
                                 "id":1
                            },
                     "amount": 111
		     },
		     {
                          "product": {
                                 "id":3
                      },
                      "amount": 12
		      }
	]
}`

**Comment by rerissondaniel** [comment]
Decidir se vai ficar em uma tela isolada ou se vai ficar em outro lugar no sistema
